services:
  website:
    build: ../lobbybot2.0-website
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - EPIC_MASTER_KEY=${EPIC_MASTER_KEY}

  manager:
    build: .
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DASHBOARD_URL=http://website:3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./accounts.csv:/app/accounts.csv
    depends_on:
      - website
